# Generated by Django 3.1.2 on 2020-10-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('minimum_bid', models.FloatField()),
                ('maximum_bid', models.FloatField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], default='OPEN', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyer')),
            ],
        ),
    ]
