# Generated by Django 3.1.2 on 2020-10-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PICKED', 'PICKED'), ('NOT PICKED', 'NOT PICKED'), ('WAITING', 'WAITING')], max_length=255)),
                ('Prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buyer')),
            ],
        ),
    ]
