# Generated by Django 3.1.2 on 2020-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PICKED', 'PICKED'), ('NOT PICKED', 'NOT PICKED'), ('WAITING', 'WAITING')], default='WAITING', max_length=255),
        ),
    ]
