export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_FAILED = 'LOGOUT_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const UPDATE_CREDENTIALS_SUCCESS = 'UPDATE_CREDENTIALS_SUCCESS'
export const UPDATE_CREDENTIALS_LOADING = 'UPDATE_CREDENTIALS_LOADING'
export const UPDATE_CREDENTIALS_FAILED = 'UPDATE_CREDENTIALS_FAILED'