export const GET_BIDS_SUCCESS = 'GET_BIDS_SUCCESS'
export const GET_BIDS_FAILED = 'GET_BIDS_FAILED'
export const GET_BIDS_LOADING = 'GET_BIDS_LOADING'

export const ADD_BID_SUCCESS = 'ADD_BID_SUCCESS'
export const ADD_BID_FAILED = 'ADD_BID_FAILED'
export const ADD_BID_LOADING = 'ADD_BID_LOADING'

export const WITHDRAW_BID_SUCCESS = 'WITHDRAW_BID_SUCCESS'
export const WITHDRAW_BID_FAILED = 'WITHDRAW_BID_FAILED'
export const WITHDRAW_BID_LOADING = 'WITHDRAW_BID_LOADING'

export const RESET = 'RESET'