export const BID_SET_CURRENT_PAGE = 'BID_SET_CURRENT_PAGE'
export const PRODUCT_SET_CURRENT_PAGE = 'PRODUCT_SET_CURRENT_PAGE'
export const PRODUCT_BID_SET_CURRENT_PAGE = 'PRODUCT_BID_SET_CURRENT_PAGE'