export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING'
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'

export const GET_PRODUCT_BIDS_SUCCESS = 'GET_PRODUCT_BIDS_SUCCESS'
export const GET_PRODUCT_BIDS_LOADING = 'GET_PRODUCT_BIDS_LOADING'
export const GET_PRODUCT_BIDS_FAILED = 'GET_PRODUCT_BIDS_FAILED'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING'
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED'

export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_LOADING = 'EDIT_PRODUCT_LOADING'
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED'

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

export const SELECT_BID_SUCCESS = 'SELECT_BID_SUCCESS'
export const SELECT_BID_LOADING = 'SELECT_BID_LOADING'
export const SELECT_BID_FAILED = 'SELECT_BID_FAILED'